ERROR - 2024-06-22 01:15:06 --> mysqli_sql_exception: Duplicate entry 'jose@gmail.com' for key 'EMAIL' in /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/app/Controllers/Usuarios.php(29): CodeIgniter\Model->insert(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Usuarios->create()
#9 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(49): require_once('/Applications/X...')
#15 {main}
CRITICAL - 2024-06-22 01:15:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'jose@gmail.com' for key 'EMAIL'
[Method: POST, Route: api/usuarios/create]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
CRITICAL - 2024-06-22 01:15:06 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'jose@gmail.com' for key 'EMAIL'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'jose\', \'rosellon\', \'1\', \'12345601\', \'2000-07-05\', \'jose@gmail.com\', \'$2y$10$0MuWujio4X.PhwchZMGJ8OeSaAV9cgdl8XCAIkidBaZD.yy2fJtju\', \'12345671\', \'1\', \'2\', \'1234\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'jose\', \'rosellon\', \'1\', \'12345601\', \'2000-07-05\', \'jose@gmail.com\', \'$2y$10$0MuWujio4X.PhwchZMGJ8OeSaAV9cgdl8XCAIkidBaZD.yy2fJtju\', \'12345671\', \'1\', \'2\', \'1234\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
 9 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
CRITICAL - 2024-06-22 01:15:06 --> [Caused by] mysqli_sql_exception: Duplicate entry 'jose@gmail.com' for key 'EMAIL'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'jose\', \'rosellon\', \'1\', \'12345601\', \'2000-07-05\', \'jose@gmail.com\', \'$2y$10$0MuWujio4X.PhwchZMGJ8OeSaAV9cgdl8XCAIkidBaZD.yy2fJtju\', \'12345671\', \'1\', \'2\', \'1234\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'jose\', \'rosellon\', \'1\', \'12345601\', \'2000-07-05\', \'jose@gmail.com\', \'$2y$10$0MuWujio4X.PhwchZMGJ8OeSaAV9cgdl8XCAIkidBaZD.yy2fJtju\', \'12345671\', \'1\', \'2\', \'1234\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'jose\', \'rosellon\', \'1\', \'12345601\', \'2000-07-05\', \'jose@gmail.com\', \'$2y$10$0MuWujio4X.PhwchZMGJ8OeSaAV9cgdl8XCAIkidBaZD.yy2fJtju\', \'12345671\', \'1\', \'2\', \'1234\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
ERROR - 2024-06-22 01:15:38 --> mysqli_sql_exception: Duplicate entry '123456012' for key 'NO_DOCUMENTO' in /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/app/Controllers/Usuarios.php(29): CodeIgniter\Model->insert(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Usuarios->create()
#9 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(49): require_once('/Applications/X...')
#15 {main}
CRITICAL - 2024-06-22 01:15:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '123456012' for key 'NO_DOCUMENTO'
[Method: POST, Route: api/usuarios/create]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
CRITICAL - 2024-06-22 01:15:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '123456012' for key 'NO_DOCUMENTO'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$1v413/x385yAEk.fxOvHU.Z6BQ3sSTWLd9lTQaStQTmPRE6r0Rpn2\', \'123456712\', \'1\', \'2\', \'1234\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$1v413/x385yAEk.fxOvHU.Z6BQ3sSTWLd9lTQaStQTmPRE6r0Rpn2\', \'123456712\', \'1\', \'2\', \'1234\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
 9 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
CRITICAL - 2024-06-22 01:15:38 --> [Caused by] mysqli_sql_exception: Duplicate entry '123456012' for key 'NO_DOCUMENTO'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$1v413/x385yAEk.fxOvHU.Z6BQ3sSTWLd9lTQaStQTmPRE6r0Rpn2\', \'123456712\', \'1\', \'2\', \'1234\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$1v413/x385yAEk.fxOvHU.Z6BQ3sSTWLd9lTQaStQTmPRE6r0Rpn2\', \'123456712\', \'1\', \'2\', \'1234\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$1v413/x385yAEk.fxOvHU.Z6BQ3sSTWLd9lTQaStQTmPRE6r0Rpn2\', \'123456712\', \'1\', \'2\', \'1234\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
ERROR - 2024-06-22 01:16:18 --> mysqli_sql_exception: Duplicate entry '123456012' for key 'NO_DOCUMENTO' in /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
#5 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Model.php(791): CodeIgniter\BaseModel->insert(Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/app/Controllers/Usuarios.php(29): CodeIgniter\Model->insert(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Usuarios->create()
#9 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(49): require_once('/Applications/X...')
#15 {main}
CRITICAL - 2024-06-22 01:16:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '123456012' for key 'NO_DOCUMENTO'
[Method: POST, Route: api/usuarios/create]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 2 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
CRITICAL - 2024-06-22 01:16:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '123456012' for key 'NO_DOCUMENTO'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$F6OSbHvjd3aW8SV192KKaebquuRkznwx49w92it11zJpoOKRiOhua\', \'123456712\', \'1\', \'2\', \'1234\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$F6OSbHvjd3aW8SV192KKaebquuRkznwx49w92it11zJpoOKRiOhua\', \'123456712\', \'1\', \'2\', \'1234\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 4 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
 9 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
CRITICAL - 2024-06-22 01:16:18 --> [Caused by] mysqli_sql_exception: Duplicate entry '123456012' for key 'NO_DOCUMENTO'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$F6OSbHvjd3aW8SV192KKaebquuRkznwx49w92it11zJpoOKRiOhua\', \'123456712\', \'1\', \'2\', \'1234\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$F6OSbHvjd3aW8SV192KKaebquuRkznwx49w92it11zJpoOKRiOhua\', \'123456712\', \'1\', \'2\', \'1234\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (\'josecar\', \'rosellon\', \'1\', \'123456012\', \'2000-07-05\', \'joseg@gmail.com\', \'$2y$10$F6OSbHvjd3aW8SV192KKaebquuRkznwx49w92it11zJpoOKRiOhua\', \'123456712\', \'1\', \'2\', \'1234\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`NOMBRE`, `APELLIDO`, `TIPO_DOCUMENTO_ID`, `NO_DOCUMENTO`, `FECHA_NACIMIENTO`, `EMAIL`, `CONTRASENA`, `TELEFONO`, `CARGO_ID`, `TORRE`, `APTO`) VALUES (:NOMBRE:, :APELLIDO:, :TIPO_DOCUMENTO_ID:, :NO_DOCUMENTO:, :FECHA_NACIMIENTO:, :EMAIL:, :CONTRASENA:, :TELEFONO:, :CARGO_ID:, :TORRE:, :APTO:)', [...], false)
 5 SYSTEMPATH/Model.php(383): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(791): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Controllers/Usuarios.php(29): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Usuarios->create()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH/Commands/Server/rewrite.php(49): require_once('/Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/public/index.php')
